"use client";
import { forwardRef, useState, useEffect } from "react";
import { motion } from "framer-motion";

type FloatingAssistantProps = {
  disabled?: boolean;
  startButtonText?: string;
  onStartCall?: () => void;
};

const FloatingAssistant = forwardRef<HTMLDivElement, FloatingAssistantProps>(
  ({ disabled, startButtonText, onStartCall }, ref) => {
    const [showTooltip, setShowTooltip] = useState(true);

    useEffect(() => {
      const timer = setTimeout(() => setShowTooltip(false), 5000);
      return () => clearTimeout(timer);
    }, []);

    return (
      <motion.div
        ref={ref}
        aria-disabled={disabled}
        animate={{
          y: disabled ? 0 : [0, -8, 0],
        }}
        transition={{
          repeat: disabled ? 0 : Infinity,
          duration: 4,
          ease: "easeInOut",
        }}
        className={`fixed bottom-20 sm:bottom-[100px] right-6 sm:right-8 z-50`}
      >
        <div className="relative group flex items-center justify-center">
          {/* Subtle glowing pulse behind the button */}
          {!disabled && (
            <>
              {/* Outer Glow */}
              <div className="absolute inset-0 rounded-full bg-orange-500 opacity-30 blur-2xl group-hover:opacity-50 transition-opacity duration-500"></div>
              
              {/* Ripple Waves */}
              <div className="absolute inset-0 rounded-full border-2 border-white/30 animate-ai-wave"></div>
              <div className="absolute inset-0 rounded-full border-2 border-white/15 animate-ai-wave-delay"></div>
            </>
          )}
          
          <button
            onClick={onStartCall}
            disabled={disabled}
            className={`relative flex items-center justify-center w-14 h-14 sm:w-16 sm:h-16 rounded-full shadow-2xl backdrop-blur-md transition-all duration-300 z-10 overflow-hidden
              ${disabled 
                ? "opacity-0 pointer-events-none translate-y-4" 
                : "bg-gradient-to-r from-orange-500 to-rose-500 hover:shadow-[0_0_25px_rgba(249,115,22,0.7)] hover:scale-115"
              }
              text-white
            `}
          >
            {/* Custom Robot Icon generated by AI matching user's image exactly */}
            <img
              src="/ai.png?v=3"
              alt="Sunny AI"
              className="w-full h-full object-contain rounded-full"
            />
          </button>
          
          {/* Tooltip - First load or hover */}
          {startButtonText && (
            <div className={`absolute right-[115%] px-4 py-3 bg-gray-900/95 text-white text-sm font-medium rounded-2xl shadow-2xl border border-white/10 whitespace-nowrap pointer-events-none transition-all duration-500 origin-right z-20
              ${showTooltip && !disabled
                ? "opacity-100 scale-100 translate-x-0" 
                : "opacity-0 scale-95 translate-x-4 group-hover:opacity-100 group-hover:scale-100 group-hover:translate-x-0 hidden sm:block"
              }
            `}>
              <div className="flex flex-col text-left">
                <span className="font-bold text-orange-400">👋 Sunny AI</span>
                <span className="text-gray-200 text-xs mt-1">{startButtonText}</span>
              </div>
              {/* Arrow pointer */}
              <div className="absolute top-1/2 -right-1.5 w-3 h-3 bg-gray-900/95 border-r border-t border-white/10 transform rotate-45 -translate-y-1/2"></div>
            </div>
          )}
        </div>
      </motion.div>
    );
  }
);

FloatingAssistant.displayName = "FloatingAssistant";
export default FloatingAssistant;
